name: Regression Tests

on:
  pull_request:
  push:
    branches: [develop]

concurrency:
  group: regression-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ENCLAVE_NAME: cdk

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4

    - name: Build docker image
      run: make build-docker
    
    - name: Save docker image to archive
      run: docker save --output /tmp/zkevm-bridge-service.tar zkevm-bridge-service
    
    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: zkevm-bridge-service
        path: /tmp/zkevm-bridge-service.tar

  deploy-cdk-stack:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build-docker-image
    steps:
    - uses: actions/checkout@v4

    - name: Checkout kurtosis-cdk repository
      uses: actions/checkout@v4
      with:
        repository: 0xPolygon/kurtosis-cdk
        path: kurtosis-cdk
        ref: v0.2.27

    - name: Install Kurtosis CDK tools
      uses: ./kurtosis-cdk/.github/actions/setup-kurtosis-cdk
    
    - name: Download archive
      uses: actions/download-artifact@v4
      with:
        name: zkevm-bridge-service
        path: /tmp
    
    - name: Load docker image
      run: |
        docker load --input /tmp/zkevm-bridge-service.tar
        docker image ls -a

    - name: Deploy kurtosis enclave
      working-directory: kurtosis-cdk
      run: |
        kurtosis run --enclave ${{ env.ENCLAVE_NAME }} . '{"args": {"zkevm_bridge_service_image": "zkevm-bridge-service:latest"}}'

    - name: Monitor verified batches
      working-directory: ./kurtosis-cdk/.github/scripts
      run: |
        ./monitor-cdk-chain.sh \
          --enclave ${{ env.ENCLAVE_NAME }} \
          --rpc-url $(kurtosis port print ${{ env.ENCLAVE_NAME }} cdk-erigon-rpc-001 rpc) 

    - name: Dump enclave
      if: ${{ !cancelled() }}
      run: kurtosis enclave dump ${{ env.ENCLAVE_NAME }} ./dump
    
    - name: Upload enclave dump
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: dump_regression_tests_${{ github.run_id }}
        path: ./dump
